image: ghcr.io/mehulagg/flutter_gitpod:latest

tasks:
  - before: |
      export PATH=/home/gitpod/Android/Sdk/tools/bin/:$PATH
      export PATH=/home/gitpod/flutter/bin/:$PATH
      echo "export PATH=$FLUTTER_HOME/bin:$ANDROID_HOME/tools/bin:$PATH" > ~/.bashrc
      flutter upgrade
      yes | sdk i java 8.0.282-open
      sdk i kotlin
      touch /home/gitpod/.android/repositories.cfg
      sdkmanager --update
      yes | sdkmanager --licenses

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - pkief.material-icon-theme
    - vscode-icons-team.vscode-icons
    - coenraads.bracket-pair-colorizer-2
