image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      export PATH=/home/gitpod/Android/Sdk/tools/bin/:$PATH
      export PATH=/home/gitpod/flutter/bin/:$PATH
    init: |
      flutter upgrade
      ./skysend-linux.bin d https://skysend.hns.siasky.net/#b-CAC5pl0IkbI0l5GWI8eCjAm6e3toD6e9BpUH2s9z347AXA+eCQNBSt5g3UWLlyNiDz30MsalpC2KuzVz75jXl4eG8AQbL8nTOZSgVpp41XymkKz
      unzip Android.zip
      rm Android.zip
      mv Android /home/gitpod
      yes | sdk i java 8.0.282-open
      sdk i kotlin
      sdkmanager --update
      yes | sdkmanager --licenses
    
vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - pkief.material-icon-theme
