image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      export PATH=/home/gitpod/Android/Sdk/tools/bin/:$PATH
      export PATH=/home/gitpod/flutter/bin/:$PATH
    init: |
      flutter upgrade
      yes | sdk i java 8.0.282-open
      sdk i kotlin
      sdkmanager --update
      yes | sdkmanager --licenses
    
vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - pkief.material-icon-theme
